### ISSUE TITLE
ModuleNotFoundError: No module named 'dsgl.models.uncertains'

### ISSUE THREAD

**Issue by PengfeiMa** [jihaoxuanye/DiseSGL#1]
训练报错：
Traceback (most recent call last):
  File "/data/test/12_DiseSGL/DiseSGL/examples/train.py", line 38, in <module>
    from dsgl.models.uncertains import UncertainSamples
ModuleNotFoundError: No module named 'dsgl.models.uncertains'

请教一下大佬，dsgl.models里是不是忘了添加UncertainSamples这个类了，执行代码报错了

**Comment by jihaoxuanye** [comment]
把这个from注释掉就好了，这个uncertain是一个另一个论文里的



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 10:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)

**Comment by jihaoxuanye** [comment]
直接走test.py吧，这个模型已经训练好了。train.py等论文中了再改改。



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 10:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
训练报错：
 Traceback (most recent call last):
 File "/data/test/12_DiseSGL/DiseSGL/examples/train.py", line 38, in 
 from dsgl.models.uncertains import UncertainSamples
 ModuleNotFoundError: No module named 'dsgl.models.uncertains'
 
请教一下大佬，dsgl.models里是不是忘了添加UncertainSamples这个类了，执行代码报错了

**Comment by PengfeiMa** [comment]
多谢大佬，train.py修改后可以训练一个epoch , test.py中缺少hhcl包，不知道是pip安装的还是导入的源码包。

**Comment by jihaoxuanye** [comment]
这个我回去看看，可能有的少改了。



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)

**Comment by PengfeiMa** [comment]
train.py训练resnet50的时候features设置了16，按说明应该是不需要设置的，但是不设置训练会报错，设置后训练一个epoch还是会报错，报错信息如下：
![image](https://github.com/user-attachments/assets/cdf25173-34ed-46a7-8f2c-ba490fe5ab04)
辛苦大佬一起看下

**Comment by jihaoxuanye** [comment]
这个test.py的有具体报错信息吗？我看都修改过了



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
多谢大佬，train.py修改后可以训练一个epoch , test.py中缺少hhcl包，不知道是pip安装的还是导入的源码包。

**Comment by jihaoxuanye** [comment]
你好，这个test.py已经修改过了。应该可以跑了



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
多谢大佬，train.py修改后可以训练一个epoch , test.py中缺少hhcl包，不知道是pip安装的还是导入的源码包。

**Comment by jihaoxuanye** [comment]
这个16是num-instance吗？还是哪个？可以截图看一下吗？
图中这个错误就是self.clu_memory没读进去数据





---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
train.py训练resnet50的时候features设置了16，按说明应该是不需要设置的，但是不设置训练会报错，设置后训练一个epoch还是会报错，报错信息如下：
 image.png (view on web)
 辛苦大佬一起看下

**Comment by jihaoxuanye** [comment]
我重新修改了train.py和test.py，再训练看看还会不会出错了。




图中的错误是train.py的195行应该读进去数据的



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
train.py训练resnet50的时候features设置了16，按说明应该是不需要设置的，但是不设置训练会报错，设置后训练一个epoch还是会报错，报错信息如下：
 image.png (view on web)
 辛苦大佬一起看下

**Comment by jihaoxuanye** [comment]
我重新修改了train和test，看还会不会出现这个错误了。






图中最本质的就是train里面的239行不应该是none



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 15:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jihaoxuanye/DiseSGL] ModuleNotFoundError: No module named'dsgl.models.uncertains' (Issue #1)




 
train.py训练resnet50的时候features设置了16，按说明应该是不需要设置的，但是不设置训练会报错，设置后训练一个epoch还是会报错，报错信息如下：
 image.png (view on web)
 辛苦大佬一起看下
